# Generated by Django 6.0.3 on 2026-03-13 13:45

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
