# Generated by Django 6.0.3 on 2026-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='mode_of_consultation',
            field=models.CharField(choices=[('ON', 'Online'), ('FF', 'Face to Face')], default='ON', max_length=2),
        ),
    ]
