# Generated by Django 6.0.3 on 2026-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
