# Generated by Django 6.0.3 on 2026-03-27 15:50

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_dailymood_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordrawing',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddField(
            model_name='vectordrawing',
            name='image_b64',
            field=models.TextField(blank=True),
        ),
    ]
