# Generated by Django 6.0.3 on 2026-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_canvas_drawings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordrawing',
            name='emotional_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
