# Generated by Django 6.0.3 on 2026-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_studenttrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttrack',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='studenttrack',
            name='url',
        ),
        migrations.AddField(
            model_name='studenttrack',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='studenttrack',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
