# Generated by Django 6.0.3 on 2026-04-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_vectordrawing_emotional_analysis'),
        ('wellness', '0005_rename_added_at_studenttrack_created_at_and_more'),
    ]

    operations = [
    ]
