# Generated by Django 6.0.3 on 2026-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0006_merge_20260407_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttrack',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/%Y/%m/%d/'),
        ),
    ]
