# Generated by Django 6.0.3 on 2026-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0009_studentphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='studentphoto',
            name='image_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentphoto',
            name='mime_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
    ]
