import { useEffect, useRef, useState, useCallback } from "react";

const sections = [
  {
    number: "1",
    title: "Introduction",
    content: [
      "The GIMI (Game Changer Emotional Management Interface) platform is committed to protecting the privacy and confidentiality of its users. This Privacy Policy explains how information is collected, used, stored, and protected when students use the platform.",
      "GIMI is designed to support the guidance department of iACADEMY Cebu by providing students with a digital space to record moods, reflect on emotions, and write journal entries during times when guidance services may not be immediately available.",
      "By using the platform, users acknowledge that they have read and understood this Privacy Policy.",
    ],
  },
  {
    number: "2",
    title: "Information We Collect",
    content: [
      "GIMI collects only the information necessary to provide its intended functionality. The types of information that may be collected include:",
    ],
    subsections: [
      {
        label: "Journal Entries",
        text: "Students may write personal reflections or journal entries within the platform.",
      },
      {
        label: "Mood Tracking Data",
        text: "Students may record their emotional state through mood logs or calendar entries.",
      },
      {
        label: "System Usage Information",
        text: "The platform may record timestamps or usage activity necessary for system functionality and monitoring.",
      },
    ],
    footer: "GIMI does not intentionally collect unnecessary personal data beyond what is required for the system to function.",
  },
  {
    number: "3",
    title: "How Information Is Used",
    content: [
      "The information collected through GIMI is used for the following purposes:",
    ],
    bullets: [
      "To allow students to track their moods and reflect through journaling",
      "To support the guidance department in identifying students who may need assistance",
      "To enable automated keyword monitoring that may generate alerts for guidance counselors when certain indicators of emotional distress appear",
      "To maintain system functionality and performance",
    ],
    footer: "The platform processes information only for purposes related to student well-being and guidance support.",
  },
  {
    number: "4",
    title: "Automated Monitoring",
    content: [
      "Journal entries submitted through the platform may be analyzed by automated systems designed to detect specific keywords associated with emotional distress or potential need for support.",
      "If certain keywords are detected, the system may generate alerts that notify authorized personnel in the guidance department.",
      "This monitoring is performed by the system and is intended solely to help ensure student well-being.",
    ],
  },
  {
    number: "5",
    title: "Access to Information",
    content: [
      "Access to collected data is restricted to protect user privacy.",
    ],
    subsections: [
      {
        label: "Student Developers",
        text: "Student developers responsible for creating the platform do not have access to individual journal entries or private user data.",
      },
      {
        label: "Authorized Guidance Personnel",
        text: "Only authorized members of the guidance department may receive alerts generated by the system when specific indicators are detected.",
      },
    ],
    footer: "Access to information is limited strictly to individuals who require it for student support purposes.",
  },
  {
    number: "6",
    title: "Data Storage and Protection",
    content: [
      "GIMI implements reasonable security measures to protect the information stored within the platform. These measures may include secure database storage, controlled system access, and authentication protocols.",
      "Despite these efforts, no online platform can guarantee complete protection from all potential security risks.",
      "The system is designed to minimize risk and protect student confidentiality as much as possible.",
    ],
  },
  {
    number: "7",
    title: "Data Retention",
    content: [
      "Information collected through the platform may be stored for as long as necessary to support the purpose of the system and assist the guidance department.",
      "Data may be removed or archived when it is no longer required for its intended purpose.",
    ],
  },
  {
    number: "8",
    title: "User Rights and Awareness",
    content: [
      "Students using the platform will be informed about how their information may be collected and processed. Before using the system, users must acknowledge that they understand the platform's privacy practices.",
      "Users are encouraged to contact the guidance department if they have concerns regarding their information or how it is handled.",
    ],
  },
  {
    number: "9",
    title: "Compliance with Philippine Privacy Regulations",
    content: [
      "The GIMI platform aims to follow the principles outlined in the Data Privacy Act of 2012, which governs the responsible handling of personal information in the Philippines.",
      "These principles include transparency, legitimate purpose, proportionality, and responsible protection of personal data.",
    ],
  },
  {
    number: "10",
    title: "Changes to This Privacy Policy",
    content: [
      "This Privacy Policy may be updated or modified as the platform develops or as institutional policies change.",
      "Users will be informed of significant updates to ensure continued transparency regarding data handling practices.",
      "Continued use of the platform after updates constitutes acknowledgment of the revised policy.",
    ],
  },
  {
    number: "11",
    title: "Contact and Concerns",
    content: [
      "For questions, concerns, or clarification regarding this Privacy Policy, students may contact the guidance department of iACADEMY Cebu.",
      "The guidance department serves as the responsible authority for addressing concerns related to the use of the GIMI platform.",
    ],
  },
];

interface PrivacyPolicyProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function PrivacyPolicy({ isOpen, onClose }: PrivacyPolicyProps) {
  const [mounted, setMounted] = useState(false);
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      setMounted(true);
      setHasScrolledToBottom(false);
    } else {
      const t = setTimeout(() => setMounted(false), 200);
      return () => clearTimeout(t);
    }
  }, [isOpen]);

  // Check if content is short enough that no scrolling is needed
  const checkIfAlreadyAtBottom = useCallback(() => {
    const el = scrollRef.current;
    if (!el) return;
    if (el.scrollHeight <= el.clientHeight + 2) {
      setHasScrolledToBottom(true);
    }
  }, []);

  useEffect(() => {
    if (mounted && isOpen) {
      // Small delay to let the DOM render before measuring
      const t = setTimeout(checkIfAlreadyAtBottom, 50);
      return () => clearTimeout(t);
    }
  }, [mounted, isOpen, checkIfAlreadyAtBottom]);

  const handleScroll = () => {
    const el = scrollRef.current;
    if (!el || hasScrolledToBottom) return;
    // Allow a small threshold (2px) for rounding
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 2) {
      setHasScrolledToBottom(true);
    }
  };

  const handleClose = () => {
    if (hasScrolledToBottom) onClose();
  };

  if (!mounted) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center px-4"
      style={{
        background: "rgba(0,0,0,0.3)",
        opacity: isOpen ? 1 : 0,
        transition: "opacity 0.2s",
      }}
      onClick={handleClose}
    >
      <div
        className="relative w-full sm:w-[520px] max-h-[80vh] flex flex-col rounded-3xl overflow-hidden bg-white"
        style={{
          boxShadow:
            "0 8px 40px rgba(30,60,100,0.18), 0 2px 8px rgba(30,60,100,0.10)",
          transform: isOpen
            ? "translateY(0) scale(1)"
            : "translateY(16px) scale(0.97)",
          transition: "transform 0.2s, opacity 0.2s",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div
          className="flex items-center px-7 pt-7 pb-5 shrink-0"
          style={{ borderBottom: "1px solid #e2ecf8" }}
        >
          <div>
            <p
              className="text-xs font-semibold tracking-widest uppercase mb-0.5"
              style={{ color: "#3a6ec4" }}
            >
              GIMI Journal · iACADEMY Cebu
            </p>
            <h2 className="text-xl font-bold text-gray-900">Privacy Policy</h2>
          </div>
        </div>

        {/* Scrollable body */}
        <div
          ref={scrollRef}
          onScroll={handleScroll}
          className="overflow-y-auto px-7 py-5 space-y-5 flex-1"
        >
          {sections.map((section) => (
            <div key={section.number}>
              {/* Section heading */}
              <div className="flex items-center gap-2.5 mb-2">
                <span
                  className="inline-flex items-center justify-center rounded-lg text-xs font-bold shrink-0 text-white"
                  style={{
                    width: 24,
                    height: 24,
                    background: "linear-gradient(135deg, #2c5aa0, #3a6ec4)",
                  }}
                >
                  {section.number}
                </span>
                <h3 className="text-sm font-bold text-gray-900">
                  {section.title}
                </h3>
              </div>

              <div className="pl-8 space-y-2">
                {/* Body paragraphs */}
                {section.content.map((para, i) => (
                  <p
                    key={i}
                    className="text-sm text-gray-700 leading-relaxed"
                  >
                    {para}
                  </p>
                ))}

                {/* Subsections (labeled blocks) */}
                {"subsections" in section && section.subsections && (
                  <div className="space-y-2 mt-1">
                    {section.subsections.map((sub, i) => (
                      <div
                        key={i}
                        className="rounded-xl px-3 py-2.5"
                        style={{
                          background: "rgba(210,235,255,0.30)",
                          borderLeft: "3px solid #3a6ec4",
                        }}
                      >
                        <p className="text-xs font-bold text-gray-800 mb-0.5">
                          {sub.label}
                        </p>
                        <p className="text-sm text-gray-700 leading-relaxed">
                          {sub.text}
                        </p>
                      </div>
                    ))}
                  </div>
                )}

                {/* Bullet list */}
                {"bullets" in section && section.bullets && (
                  <ul className="space-y-1.5 mt-1">
                    {section.bullets.map((b, i) => (
                      <li
                        key={i}
                        className="flex items-start gap-2 text-sm text-gray-700"
                      >
                        <span
                          className="mt-2 shrink-0 rounded-full"
                          style={{ width: 5, height: 5, background: "#3a6ec4" }}
                        />
                        {b}
                      </li>
                    ))}
                  </ul>
                )}

                {/* Footer paragraph */}
                {"footer" in section && section.footer && (
                  <p className="text-sm text-gray-700 leading-relaxed mt-2">
                    {section.footer}
                  </p>
                )}
              </div>

              <div
                className="mt-4"
                style={{ borderBottom: "1px solid #e2ecf8" }}
              />
            </div>
          ))}
        </div>

        {/* Footer button */}
        <div
          className="px-7 py-5 shrink-0"
          style={{ borderTop: "1px solid #e2ecf8" }}
        >
          {/* Scroll-down hint that disappears once scrolled */}
          {!hasScrolledToBottom && (
            <p
              className="text-xs text-center mb-3 font-medium animate-pulse"
              style={{ color: "#7D9DC9" }}
            >
              ↓ Please scroll down to read the full policy before continuing ↓
            </p>
          )}

          <button
            onClick={handleClose}
            disabled={!hasScrolledToBottom}
            className="w-full rounded-xl py-3 font-semibold text-sm transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-offset-2"
            style={{
              background: hasScrolledToBottom
                ? "linear-gradient(90deg, #2c5aa0 0%, #3a6ec4 100%)"
                : "linear-gradient(90deg, #94a8c4 0%, #a8b8d0 100%)",
              boxShadow: hasScrolledToBottom
                ? "0 4px 16px rgba(44,90,160,0.30)"
                : "none",
              color: hasScrolledToBottom ? "#fff" : "#d0d6e0",
              cursor: hasScrolledToBottom ? "pointer" : "not-allowed",
            }}
          >
            {hasScrolledToBottom
              ? "I Understand"
              : "Read Full Policy to Continue"}
          </button>
        </div>
      </div>
    </div>
  );
}