import { useEffect, useRef, useState, useCallback } from "react";

const sections = [
  {
    number: "1",
    title: "Acceptance of Terms",
    content: [
      "By accessing or using the GIMI platform, users agree to comply with and be bound by these Terms and Conditions. If a user does not agree with any part of these terms, they should discontinue use of the platform.",
      "GIMI is intended for students of iACADEMY Cebu and is designed to support the guidance department in assisting students with emotional reflection and mood tracking.",
    ],
  },
  {
    number: "2",
    title: "Purpose of the Platform",
    content: [
      "GIMI (Game Changer Emotional Management Interface) is a web-based platform that allows students to record emotions, track moods, and write journal entries.",
      "The platform exists to support the guidance department by helping students manage their emotions during times when counseling services may not be immediately available.",
    ],
  },
  {
    number: "3",
    title: "User Eligibility",
    content: [
      "The platform is intended for use by students enrolled at iACADEMY Cebu. By using the platform, users confirm that they are authorized to access the system through their student credentials.",
    ],
  },
  {
    number: "4",
    title: "User Responsibilities",
    content: [
      "Users are expected to use the platform responsibly and in accordance with school policies.",
      "Users must not:",
    ],
    bullets: [
      "Attempt to access accounts or data belonging to other users",
      "Attempt to manipulate, exploit, or disrupt the system",
      "Use the platform to post harmful, abusive, or inappropriate content",
      "Use the platform for illegal activities",
    ],
    footer:
      "Any misuse of the platform may result in restricted access or disciplinary action according to school policies.",
  },
  {
    number: "5",
    title: "Privacy and Data Handling",
    content: [
      "The platform collects information necessary for its operation, including journal entries, mood tracking data, and system timestamps.",
      "Journal entries are securely stored within the system and are not accessible to student developers or unauthorized individuals.",
      "Access to system alerts is restricted to authorized guidance department personnel when necessary.",
      "All collected data is handled responsibly and stored securely to protect student confidentiality.",
    ],
  },
  {
    number: "6",
    title: "Automated System Alerts",
    content: [
      "GIMI includes automated monitoring mechanisms that analyze journal entries for specific keywords that may indicate emotional distress.",
      "If such keywords are detected, the system may notify authorized guidance personnel so that appropriate support can be provided.",
      "These alerts are generated by the system and are intended solely to help the guidance department identify students who may need assistance.",
    ],
  },
  {
    number: "7",
    title: "Data Security",
    content: [
      "The platform implements reasonable technical and administrative safeguards to protect user data. These safeguards may include secure storage systems, restricted administrative access, and authentication controls.",
      "While efforts are made to maintain data security, users acknowledge that no online system can guarantee complete protection from all security risks.",
    ],
  },
  {
    number: "8",
    title: "System Availability",
    content: [
      "GIMI may occasionally experience interruptions due to system maintenance, updates, or technical issues. The developers and administrators do not guarantee uninterrupted service at all times.",
      "Users are encouraged to seek assistance directly from the guidance department if immediate support is required.",
    ],
  },
  {
    number: "9",
    title: "Modifications to the Terms",
    content: [
      "These Terms and Conditions may be updated as the platform evolves or as institutional policies change.",
      "Users will be notified of significant updates, and continued use of the platform constitutes acceptance of any revised terms.",
    ],
  },
];

interface TermsAndConditionsProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TermsAndConditions({ isOpen, onClose }: TermsAndConditionsProps) {
  const [mounted, setMounted] = useState(false);
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      setMounted(true);
      setHasScrolledToBottom(false);
    } else {
      const t = setTimeout(() => setMounted(false), 200);
      return () => clearTimeout(t);
    }
  }, [isOpen]);

  // Check if content is short enough that no scrolling is needed
  const checkIfAlreadyAtBottom = useCallback(() => {
    const el = scrollRef.current;
    if (!el) return;
    if (el.scrollHeight <= el.clientHeight + 2) {
      setHasScrolledToBottom(true);
    }
  }, []);

  useEffect(() => {
    if (mounted && isOpen) {
      const t = setTimeout(checkIfAlreadyAtBottom, 50);
      return () => clearTimeout(t);
    }
  }, [mounted, isOpen, checkIfAlreadyAtBottom]);

  const handleScroll = () => {
    const el = scrollRef.current;
    if (!el || hasScrolledToBottom) return;
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 2) {
      setHasScrolledToBottom(true);
    }
  };

  const handleClose = () => {
    if (hasScrolledToBottom) onClose();
  };

  if (!mounted) return null;

  return (
    /* Overlay */
    <div
      className="fixed inset-0 z-50 flex items-center justify-center px-4"
      style={{
        background: "rgba(0,0,0,0.3)",
        opacity: isOpen ? 1 : 0,
        transition: "opacity 0.2s",
      }}
      onClick={handleClose}
    >
      {/* Popup card */}
      <div
        className="relative w-full sm:w-[520px] max-h-[80vh] flex flex-col rounded-3xl overflow-hidden bg-white"
        style={{
          boxShadow: "0 8px 40px rgba(30,60,100,0.18), 0 2px 8px rgba(30,60,100,0.10)",
          transform: isOpen ? "translateY(0) scale(1)" : "translateY(16px) scale(0.97)",
          transition: "transform 0.2s, opacity 0.2s",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div
          className="flex items-center px-7 pt-7 pb-5 shrink-0"
          style={{ borderBottom: "1px solid #e2ecf8" }}
        >
          <div>
            <p className="text-xs font-semibold tracking-widest uppercase mb-0.5" style={{ color: "#3a6ec4" }}>
              GIMI Journal
            </p>
            <h2 className="text-xl font-bold text-gray-900">Terms &amp; Conditions</h2>
          </div>
        </div>

        {/* Scrollable body */}
        <div
          ref={scrollRef}
          onScroll={handleScroll}
          className="overflow-y-auto px-7 py-5 space-y-5 flex-1"
        >
          {sections.map((section) => (
            <div key={section.number}>
              {/* Section title row */}
              <div className="flex items-center gap-2.5 mb-2">
                <span
                  className="inline-flex items-center justify-center rounded-lg text-xs font-bold shrink-0 text-white"
                  style={{
                    width: 24,
                    height: 24,
                    background: "linear-gradient(135deg, #2c5aa0, #3a6ec4)",
                  }}
                >
                  {section.number}
                </span>
                <h3 className="text-sm font-bold text-gray-900">{section.title}</h3>
              </div>

              {/* Body text */}
              <div className="pl-8 space-y-2">
                {section.content.map((para, i) => (
                  <p key={i} className="text-sm text-gray-700 leading-relaxed">
                    {para}
                  </p>
                ))}

                {section.bullets && (
                  <ul className="space-y-1.5 mt-1">
                    {section.bullets.map((b, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                        <span
                          className="mt-2 shrink-0 rounded-full"
                          style={{ width: 5, height: 5, background: "#3a6ec4" }}
                        />
                        {b}
                      </li>
                    ))}
                  </ul>
                )}

                {"footer" in section && section.footer && (
                  <p className="text-sm text-gray-700 leading-relaxed mt-2">
                    {section.footer}
                  </p>
                )}
              </div>

              {/* Divider */}
              <div className="mt-4" style={{ borderBottom: "1px solid #e2ecf8" }} />
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="px-7 py-5 shrink-0" style={{ borderTop: "1px solid #e2ecf8" }}>
          {/* Scroll-down hint */}
          {!hasScrolledToBottom && (
            <p
              className="text-xs text-center mb-3 font-medium animate-pulse"
              style={{ color: "#7D9DC9" }}
            >
              ↓ Please scroll down to read all terms before continuing ↓
            </p>
          )}

          <button
            onClick={handleClose}
            disabled={!hasScrolledToBottom}
            className="w-full rounded-xl py-3 font-semibold text-sm transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-offset-2"
            style={{
              background: hasScrolledToBottom
                ? "linear-gradient(90deg, #2c5aa0 0%, #3a6ec4 100%)"
                : "linear-gradient(90deg, #94a8c4 0%, #a8b8d0 100%)",
              boxShadow: hasScrolledToBottom
                ? "0 4px 16px rgba(44,90,160,0.30)"
                : "none",
              color: hasScrolledToBottom ? "#fff" : "#d0d6e0",
              cursor: hasScrolledToBottom ? "pointer" : "not-allowed",
            }}
          >
            {hasScrolledToBottom ? "I Understand" : "Read All Terms to Continue"}
          </button>
        </div>
      </div>
    </div>
  );
}