# Generated by Django 6.0.3 on 2026-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='ai_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
