# Generated by Django 6.0.3 on 2026-03-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_journalentry_ai_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='ai_reply',
            new_name='ai_chat_response',
        ),
    ]
