# Generated by Django 6.0.3 on 2026-04-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_activecondition_hospitalizationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyflag',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
