# Generated by Django 6.0.3 on 2026-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_safetyflag_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyflag',
            name='source',
            field=models.CharField(choices=[('CHAT', 'Chat Message'), ('JOURNAL', 'Journal Entry')], default='CHAT', max_length=10),
        ),
    ]
