# Generated by Django 6.0.3 on 2026-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('NURSE', 'Nurse'), ('SECURITY', 'Security'), ('COUNSELOR', 'Counselor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
