name: Django Test

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: ./backend


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django pytest pytest-django

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: core.settings
        run: |
         pytest users/test.py
